add_test([=[CircularBufferTest.ConstructorWithElement]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.ConstructorWithElement]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.ConstructorWithElement]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.CopyConstructor]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.CopyConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.CopyConstructor]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.PushBack]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.PushBack]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.PushBack]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.PushFront]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.PushFront]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.PushFront]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.PopBack]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.PopBack]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.PopBack]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.PopFront]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.PopFront]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.PopFront]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.AtMethod]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.AtMethod]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.AtMethod]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.AtMethodOutOfRange]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.AtMethodOutOfRange]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.AtMethodOutOfRange]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.Linearize]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.Linearize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.Linearize]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.IsLinearized]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.IsLinearized]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.IsLinearized]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.Rotate]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.Rotate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.Rotate]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.Resize]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.Resize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.Resize]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.ResizeSmallerThanCurrentSize]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.ResizeSmallerThanCurrentSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.ResizeSmallerThanCurrentSize]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.Clear]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.Clear]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.Clear]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.Insert]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.Insert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.Insert]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.Erase]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.Erase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.Erase]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.Swap]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.Swap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.Swap]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.AssignmentOperator]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.AssignmentOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.AssignmentOperator]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.EqualityOperator]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.EqualityOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.EqualityOperator]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.InequalityOperator]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.InequalityOperator]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.InequalityOperator]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.SetCapacity]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.SetCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.SetCapacity]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.ResizeSmaller]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.ResizeSmaller]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.ResizeSmaller]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.InsertMiddle]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.InsertMiddle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.InsertMiddle]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.InsertEnd]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.InsertEnd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.InsertEnd]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.EraseMiddle]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.EraseMiddle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.EraseMiddle]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.EraseEnd]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.EraseEnd]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.EraseEnd]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.SwapDifferentCapacity]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.SwapDifferentCapacity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.SwapDifferentCapacity]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CircularBufferTest.AssignmentOperatorMultipleElements]=]  [==[/mnt/d/с++/1b-cmake/main_test]==] [==[--gtest_filter=CircularBufferTest.AssignmentOperatorMultipleElements]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CircularBufferTest.AssignmentOperatorMultipleElements]=]  PROPERTIES WORKING_DIRECTORY [==[/mnt/d/с++/1b-cmake]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  main_test_TESTS CircularBufferTest.ConstructorWithElement CircularBufferTest.CopyConstructor CircularBufferTest.PushBack CircularBufferTest.PushFront CircularBufferTest.PopBack CircularBufferTest.PopFront CircularBufferTest.AtMethod CircularBufferTest.AtMethodOutOfRange CircularBufferTest.Linearize CircularBufferTest.IsLinearized CircularBufferTest.Rotate CircularBufferTest.Resize CircularBufferTest.ResizeSmallerThanCurrentSize CircularBufferTest.Clear CircularBufferTest.Insert CircularBufferTest.Erase CircularBufferTest.Swap CircularBufferTest.AssignmentOperator CircularBufferTest.EqualityOperator CircularBufferTest.InequalityOperator CircularBufferTest.SetCapacity CircularBufferTest.ResizeSmaller CircularBufferTest.InsertMiddle CircularBufferTest.InsertEnd CircularBufferTest.EraseMiddle CircularBufferTest.EraseEnd CircularBufferTest.SwapDifferentCapacity CircularBufferTest.AssignmentOperatorMultipleElements)
